// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("GrupoUsuarioPermissao", b =>
                {
                    b.Property<int>("GrupoUsuarioListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissaoListMyPropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrupoUsuarioListId", "PermissaoListMyPropertyId");

                    b.HasIndex("PermissaoListMyPropertyId");

                    b.ToTable("GrupoUsuarioPermissao");
                });

            modelBuilder.Entity("GrupoUsuarioUsuario", b =>
                {
                    b.Property<int>("GrupoUsuarioListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrupoUsuarioListId", "UsuarioListId");

                    b.HasIndex("UsuarioListId");

                    b.ToTable("GrupoUsuarioUsuario");
                });

            modelBuilder.Entity("Models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProduto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Novo"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Usado"
                        });
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalDosProdutos")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAcrescimo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorDesconto")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorFrete")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Models.ContasAPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAPagar")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorPago")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("ContasAPagar");
                });

            modelBuilder.Entity("Models.ContasAReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAReceber")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorRecebido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContasAReceber");
                });

            modelBuilder.Entity("Models.DepartamentoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("DepartamentoProduto");
                });

            modelBuilder.Entity("Models.FixaKardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EstoqueAnterior")
                        .HasColumnType("REAL");

                    b.Property<double>("EstoqueAtual")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<int?>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("FixaKardex");
                });

            modelBuilder.Entity("Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Models.GrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartamentoProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoProdutoId");

                    b.ToTable("GrupoProduto");
                });

            modelBuilder.Entity("Models.GrupoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GrupoUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Operador de caixa"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Estoquista"
                        });
                });

            modelBuilder.Entity("Models.ItemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAcrescimo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorDesconto")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorFrete")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemCompra");
                });

            modelBuilder.Entity("Models.ItemContasAPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContasAReceberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContasAReceberId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItemContasAPagar");
                });

            modelBuilder.Entity("Models.ItemContasAReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContasAPagarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContasAReceberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContasAPagarId");

                    b.HasIndex("ContasAReceberId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItemContasAReceber");
                });

            modelBuilder.Entity("Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAcrescimo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorDesconto")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("REAL");

                    b.Property<int?>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItemVenda");
                });

            modelBuilder.Entity("Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Estoque")
                        .HasColumnType("REAL");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("Preco")
                        .HasColumnType("REAL");

                    b.Property<int?>("SubGrupoProdutoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("SubGrupoProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Models.SubGrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("GrupoProdutoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoProdutoId");

                    b.ToTable("SubGrupoProduto");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Administrador",
                            NomeUsuario = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "Vendedor",
                            NomeUsuario = "vendedor",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalDosProdutos")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAcrescimo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorDesconto")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("GrupoUsuarioPermissao", b =>
                {
                    b.HasOne("Models.GrupoUsuario", null)
                        .WithMany()
                        .HasForeignKey("GrupoUsuarioListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoListMyPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuarioUsuario", b =>
                {
                    b.HasOne("Models.GrupoUsuario", null)
                        .WithMany()
                        .HasForeignKey("GrupoUsuarioListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Compra", b =>
                {
                    b.HasOne("Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Models.ContasAPagar", b =>
                {
                    b.HasOne("Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Models.ContasAReceber", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Models.FixaKardex", b =>
                {
                    b.HasOne("Models.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId");

                    b.HasOne("Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId");

                    b.Navigation("Compra");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Models.GrupoProduto", b =>
                {
                    b.HasOne("Models.DepartamentoProduto", "DepartamentoProduto")
                        .WithMany()
                        .HasForeignKey("DepartamentoProdutoId");

                    b.Navigation("DepartamentoProduto");
                });

            modelBuilder.Entity("Models.ItemCompra", b =>
                {
                    b.HasOne("Models.Compra", "Compra")
                        .WithMany("ItemCompra")
                        .HasForeignKey("CompraId");

                    b.HasOne("Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Compra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Models.ItemContasAPagar", b =>
                {
                    b.HasOne("Models.ContasAReceber", "ContasAReceber")
                        .WithMany()
                        .HasForeignKey("ContasAReceberId");

                    b.HasOne("Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId");

                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("ContasAReceber");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.ItemContasAReceber", b =>
                {
                    b.HasOne("Models.ContasAPagar", null)
                        .WithMany("ItemContasAPagarList")
                        .HasForeignKey("ContasAPagarId");

                    b.HasOne("Models.ContasAReceber", "ContasAReceber")
                        .WithMany("ItemContasAReceberList")
                        .HasForeignKey("ContasAReceberId");

                    b.HasOne("Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId");

                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("ContasAReceber");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.ItemVenda", b =>
                {
                    b.HasOne("Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("Models.Venda", "Venda")
                        .WithMany("ItemVenda")
                        .HasForeignKey("VendaId");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Models.Produto", b =>
                {
                    b.HasOne("Models.CategoriaProduto", "CategoriaProduto")
                        .WithMany()
                        .HasForeignKey("CategoriaProdutoId");

                    b.HasOne("Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("Models.SubGrupoProduto", "SubGrupoProduto")
                        .WithMany()
                        .HasForeignKey("SubGrupoProdutoId");

                    b.Navigation("CategoriaProduto");

                    b.Navigation("Marca");

                    b.Navigation("SubGrupoProduto");
                });

            modelBuilder.Entity("Models.SubGrupoProduto", b =>
                {
                    b.HasOne("Models.GrupoProduto", "GrupoProduto")
                        .WithMany()
                        .HasForeignKey("GrupoProdutoId");

                    b.Navigation("GrupoProduto");
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Models.Compra", b =>
                {
                    b.Navigation("ItemCompra");
                });

            modelBuilder.Entity("Models.ContasAPagar", b =>
                {
                    b.Navigation("ItemContasAPagarList");
                });

            modelBuilder.Entity("Models.ContasAReceber", b =>
                {
                    b.Navigation("ItemContasAReceberList");
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.Navigation("ItemVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
