# Generated by Django 5.0.6 on 2024-06-27 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0002_initial'),
        ('gestao_de_projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDeTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'status de tarefa',
                'verbose_name_plural': 'statuss de tarefas',
                'db_table': 'status_de_tarefa',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_detalhada', models.TextField(blank=True, null=True)),
                ('anexo', models.JSONField(blank=True, default=list)),
                ('peso', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('prioridade', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'db_table': 'tarefa',
            },
        ),
        migrations.CreateModel(
            name='HistoriaDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_detalhada', models.TextField(default='Situação:\n\n\nSolução proposta:\n\n')),
                ('anexo', models.JSONField(blank=True, default=list)),
                ('peso', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('prioridade', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('participantes', models.ManyToManyField(related_name='historias_de_usuario_participantes', to='configuracao.usuario')),
            ],
            options={
                'verbose_name': 'historia de usuário',
                'verbose_name_plural': 'historias de usuários',
                'db_table': 'historia_de_usuario',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('automatico', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='configuracao.usuario')),
                ('historia_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='gestao_de_projeto.historiadeusuario')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('participantes', models.ManyToManyField(related_name='projetos_participantes', to='configuracao.usuario')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'db_table': 'projeto',
            },
        ),
        migrations.AddField(
            model_name='historiadeusuario',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_de_usuario', to='gestao_de_projeto.projeto'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('entregue', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='gestao_de_projeto.projeto')),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='StatusDeHistoriaDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'status de historia de usuário',
                'verbose_name_plural': 'statuss de historias de usuários',
                'db_table': 'status_de_historia_de_usuario',
                'indexes': [models.Index(fields=['descricao'], name='idx_desc_stat_de_hist_de_usu')],
            },
        ),
        migrations.AddConstraint(
            model_name='statusdehistoriadeusuario',
            constraint=models.UniqueConstraint(fields=('descricao',), name='unique_desc_stat_de_hist_de_usu'),
        ),
        migrations.AddField(
            model_name='historiadeusuario',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_de_usuario', to='gestao_de_projeto.statusdehistoriadeusuario'),
        ),
        migrations.AddIndex(
            model_name='statusdetarefa',
            index=models.Index(fields=['descricao'], name='idx_desc_stat_de_tarefa'),
        ),
        migrations.AddConstraint(
            model_name='statusdetarefa',
            constraint=models.UniqueConstraint(fields=('descricao',), name='unique_desc_stat_de_tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='historia_de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gestao_de_projeto.historiadeusuario'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='participantes',
            field=models.ManyToManyField(related_name='tarefas_participantes', to='configuracao.usuario'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='gestao_de_projeto.projeto'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='gestao_de_projeto.sprint'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='gestao_de_projeto.statusdetarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='testadores',
            field=models.ManyToManyField(related_name='tarefas_testadores', to='configuracao.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='gestao_de_projeto.tarefa'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['nome'], name='idx_nome_projeto'),
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome_projeto'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['titulo'], name='idx_titulo_sprint'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('titulo',), name='unique_titulo_sprint'),
        ),
        migrations.AddIndex(
            model_name='historiadeusuario',
            index=models.Index(fields=['titulo'], name='idx_titulo_historia_de_usuario'),
        ),
        migrations.AddConstraint(
            model_name='historiadeusuario',
            constraint=models.UniqueConstraint(fields=('titulo',), name='unique_titulo_historia_de_usuario'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['titulo'], name='idx_titulo_tarefa'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.UniqueConstraint(fields=('titulo',), name='unique_titulo_tarefa'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['descricao'], name='idx_descricao_comentario'),
        ),
        migrations.AddConstraint(
            model_name='comentario',
            constraint=models.UniqueConstraint(fields=('descricao',), name='unique_descricao_comentario'),
        ),
    ]
