version: '3.8'

services:
  aspnetcore:
    build:
      context: ../backend/aspnetcore
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - erp-network

  djangoninja:
    build:
      context: ../backend/djangoninja
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - erp-network

  angular:
    build:
      context: ../frontend/angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - erp-network

  # frontend_flutter:
  #   build:
  #     context: ../frontend/frontend_flutter
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - erp-network

  database:
    build:
      context: ../database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - erp-network

networks:
  erp-network:

volumes:
  db-data:
