# Generated by Django 5.0.6 on 2024-06-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='idx_nome'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome'),
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
