# Generated by Django 5.0.6 on 2024-06-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_produto_options_produto_idx_nome_and_more'),
    ]

    operations = [
    ]
