# Generated by Django 5.0.6 on 2024-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'db_table': 'permissao',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_usuario', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('url_foto', models.CharField(blank=True, max_length=150, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='GrupoDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grupo de usuário',
                'verbose_name_plural': 'grupos de usuários',
                'db_table': 'grupo_de_usuario',
                'indexes': [models.Index(fields=['descricao'], name='idx_desc_grupo_de_usuario')],
            },
        ),
        migrations.AddConstraint(
            model_name='grupodeusuario',
            constraint=models.UniqueConstraint(fields=('descricao',), name='unique_des_grupo_de_usuario'),
        ),
        migrations.AddIndex(
            model_name='permissao',
            index=models.Index(fields=['descricao'], name='idx_descricao_permissao'),
        ),
        migrations.AddConstraint(
            model_name='permissao',
            constraint=models.UniqueConstraint(fields=('descricao',), name='unique_descricao_permissao'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(related_name='usuario_usuarios_de_grupos', to='configuracao.grupodeusuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nome_usuario'], name='idx_nome_usuario'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('nome_usuario',), name='unique_nome_usuario'),
        ),
    ]
